### ISSUE TITLE
Port

### ISSUE THREAD

**Issue by TromboneFreak** [aunefyren/plex-wrapped#17]
I swear I'm not trying to be a bother, but I'm already using port 80 and when I change the port (using Docker Compose), I can't ever get the landing page to connect.

Is it possible to change the port, and if so, how? I planned on using a reverse proxy. Thanks!

**Comment by aunefyren** [comment]
There are several ways to achieve this, including changing the web port of the webserver running in the Docker container, but I think the easisest is just to have a port translation into the container. The docker-compose.yml example below has port 5050 on the host briged to port 80 in the container.

```
version: '3'
services:
  wrapped:
    image: aunefyren/plex-wrapped:latest
    container_name: wrapped
    network_mode: bridge
    ports:
     - '5050:80'
```
