### ISSUE TITLE
Redirects admin page to internal docker ip on remote server

### ISSUE THREAD

**Issue by WantedFreak** [aunefyren/plex-wrapped#8]
Hello,

I installed plex-wrapped with docker and nginx for ssl-termination on a remote server.
When accessing /admin it returns with a 301 http://172.17.0.3/admin so no way to actually reach it.

How do I stop it from redirecting to an unreachable ip?

**Comment by aunefyren** [comment]
'/admin' is acutally /admin/index.html. Does that work?

**Comment by WantedFreak** [comment]
It did work! Thank you @aunefyren

**Comment by aunefyren** [comment]
@WantedFreak do you have a line similar to this in your Nginx configuration for Plex Wrapped? `index index.html;`

**Comment by WantedFreak** [comment]
I do not, its just a single proxy pass
```
    location / {
        proxy_pass http://172.17.0.3:80;
	access_log  /var/log/nginx/wrapped.log;
    }
```

**Comment by WantedFreak** [comment]
No it still redirect to http://172.17.0.3/admin/

172.17.0.3 is the internal docker network on another server across the internet

**Comment by WantedFreak** [comment]
Actually https://domain.tld/admin/ works while http://domain.tld/admin does not.
Either changing the links to `./admin/` instead of `./admin` or get apache to not rewrite the url would solve this i think

**Comment by aunefyren** [comment]
Maybe, @WantedFreak. I'm not sure. I tried recreating the issue, but can't seem to.
Here is my config, no issues:

docker-compose.yml:
```
version: '3'
services:
  web:
    image: nginx:latest
    container_name: nginx
    volumes:
      - "/media/CASE/Nginx:/etc/nginx/conf.d"
    #  - "/media/CASE/Nginx/html:/var/www/html"
    ports:
      - "80:80"
    environment:
      - NGINX_PORT=80
      - PUID=1000
      - PGID=1000
    networks:
      - wrapped
  wrapped:
    image: aunefyren/plex-wrapped:latest
    container_name: wrapped
    expose:
      - "80"
    networks:
      - wrapped
networks:
  wrapped:
```

default.conf:

```
server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    #access_log  /var/log/nginx/host.access.log  main;

    location / {
        proxy_pass http://172.26.0.3:80;
        index  index.html index.htm;
    }

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # proxy the PHP scripts to Apache listening on 127.0.0.1:80
    #
    #location ~ \.php$ {
    #    proxy_pass   http://127.0.0.1;
    #}

    # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
    #
    #location ~ \.php$ {
    #    root           html;
    #    fastcgi_pass   127.0.0.1:9000;
    #    fastcgi_index  index.php;
    #    fastcgi_param  SCRIPT_FILENAME  /scripts$fastcgi_script_name;
    #    include        fastcgi_params;
    #}

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    #location ~ /\.ht {
    #    deny  all;
    #}
}
```
